<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="212" started-at="2019-02-28T19:16:22Z" finished-at="2019-02-28T19:16:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="212" started-at="2019-02-28T19:16:22Z" finished-at="2019-02-28T19:16:23Z">
      <class name="com.NumberOperationTest.ReverseIntegerTest">
        <test-method status="FAIL" signature="ReverseTest(int, int)[pri:0, instance:com.NumberOperationTest.ReverseIntegerTest@5034c75a]" name="ReverseTest" duration-ms="49" started-at="2019-02-28T19:16:23Z" data-provider="dp" finished-at="2019-02-28T19:16:23Z">
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[[I cannot be cast to [Ljava.lang.Object;]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
at org.testng.internal.reflect.MethodMatcherException.stringify(MethodMatcherException.java:87)
at org.testng.internal.reflect.MethodMatcherException.generateMessage(MethodMatcherException.java:70)
at org.testng.internal.reflect.MethodMatcherException.generateMessage(MethodMatcherException.java:49)
at org.testng.internal.reflect.MethodMatcherException.<init>(MethodMatcherException.java:17)
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReverseTest -->
      </class> <!-- com.NumberOperationTest.ReverseIntegerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
